name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest git tag
        id: get-tag
        run: |
          TAG=$(git describe --tags --abbrev=0)
          echo "::set-env name=TAG::${TAG}"

      - name: Get git log output
        id: git-log
        run: |
          echo "::set-env name=RELEASE_NOTES::$(git log ${{ steps.get-tag.outputs.TAG }}..HEAD --pretty=format:'* %s')"

      - name: Create Release
        run: |
          gh release create ${{ steps.get-tag.outputs.TAG }} --title "${{ steps.get-tag.outputs.TAG }}" --notes "${{ steps.git-log.outputs.RELEASE_NOTES }}" --repo owner/repo-name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
