name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: release-note-example.md
          path: ./

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./release-note-example.md
          token: ${{ secrets.GITHUB_TOKEN }}