name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get the latest tag
        id: get_tag
        run: |
          TAG=$(git describe --tags --abbrev=0 || echo 'v0.0.0')
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: release_notes
        run: |
          git log "${{ env.TAG }}..HEAD" --pretty=format:'* %s' > release_notes.md
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          cat release_notes.md >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create Release
        run: |
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases \
            -d '{
              "tag_name": "'"${{ env.TAG }}"'",
              "name": "Release '"${{ env.TAG }}"'",
              "body": "'"${{ env.RELEASE_NOTES }}"'",
              "draft": false,
              "prerelease": false
            }'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
